services:
  - type: web
    name: izdihar-club
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run preview -- --host 0.0.0.0 --port $PORT
    envVars:
      - key: NODE_VERSION
        value: 18
